asyncapi: 3.0.0
info:
  title: MultiStack API
  version: 0.0.1
  description: API for stacks with push and pop operations
defaultContentType: application/json
servers:
  production:
    host: 127.0.0.1
    protocol: mqtt
    description: Test broker
    variables:
      port:
        description: MQTT port
        default: "1883"
        enum:
          - "1883"
operations:
  create:
    action: receive
    channel:
      "$ref": "#/channels/create"
    reply:
      channel:
        "$ref": "#/channels/create_response"
  push:
    action: receive
    channel:
      "$ref": "#/channels/push"
  pop:
    action: receive
    channel:
      "$ref": "#/channels/pop"
    reply:
      channel:
        "$ref": "#/channels/pop_response"
  pop_response:
    action: send
    channel:
      "$ref": "#/channels/pop_response"
  create_response:
    action: send
    channel:
      "$ref": "#/channels/create_response"
