asyncapi: 3.0.0

info:
  title: KIM API
  version: 0.0.1
  description: KIM API

defaultContentType: application/json

servers:
  production:
    host: 127.0.0.1
    protocol: mqtt
    description: Test broker
    variables:
      port:
        description: MQTT port
        default: "1883"
        enum:
          - "1883"

operations:
  functionpoint-req:
    action: receive
    channel:
      $ref: "#/channels/functionpoint-req"
    reply:
      channel:
        $ref: "#/channels/functionpoint-resp"

  functionpoint-resp:
    action: send
    channel:
      $ref: "#/channels/functionpoint-resp"

  functionpoints-req:
    action: receive
    channel:
      $ref: "#/channels/functionpoints-req"
    reply:
      channel:
        $ref: "#/channels/functionpoints-resp"

  functionpoints-resp:
    action: send
    channel:
      $ref: "#/channels/functionpoints-resp"

  function-req:
    action: receive
    channel:
      $ref: "#/channels/function-req"
    reply:
      channel:
        $ref: "#/channels/function-resp"

  function-resp:
    action: send
    channel:
      $ref: "#/channels/function-resp"

  functions-req:
    action: receive
    channel:
      $ref: "#/channels/functions-req"
    reply:
      channel:
        $ref: "#/channels/functions-resp"

  functions-resp:
    action: send
    channel:
      $ref: "#/channels/functions-resp"

  location-req:
    action: receive
    channel:
      $ref: "#/channels/location-req"
    reply:
      channel:
        $ref: "#/channels/location-resp"

  location-resp:
    action: send
    channel:
      $ref: "#/channels/location-resp"

  locations-req:
    action: receive
    channel:
      $ref: "#/channels/locations-req"
    reply:
      channel:
        $ref: "#/channels/locations-resp"

  locations-resp:
    action: send
    channel:
      $ref: "#/channels/locations-resp"

  functionpoint-write-ind:
    action: send
    channel:
      $ref: "#/channels/functionpoint-write-ind"

  functionpoint-write-req:
    action: receive
    channel:
      $ref: "#/channels/functionpoint-write-req"
