asyncapi: 3.0.0

info:
  title: KIM API
  version: 0.0.1
  description: KIM API

defaultContentType: application/json

servers:
  production:
    host: 127.0.0.1
    protocol: mqtt
    description: Test broker
    variables:
      port:
        description: MQTT port
        default: "1883"
        enum:
          - "1883"

operations:
  datapoint-request:
    action: receive
    channel:
      $ref: "#/channels/datapoint-request"
    reply:
      channel:
        $ref: "#/channels/datapoint-response"

  datapoint-response:
    action: send
    channel:
      $ref: "#/channels/datapoint-response"

  datapoints-request:
    action: receive
    channel:
      $ref: "#/channels/datapoints-request"
    reply:
      channel:
        $ref: "#/channels/datapoints-response"

  datapoints-response:
    action: send
    channel:
      $ref: "#/channels/datapoints-response"

  function-request:
    action: receive
    channel:
      $ref: "#/channels/function-request"
    reply:
      channel:
        $ref: "#/channels/function-response"

  function-response:
    action: send
    channel:
      $ref: "#/channels/function-response"

  functions-request:
    action: receive
    channel:
      $ref: "#/channels/functions-request"
    reply:
      channel:
        $ref: "#/channels/functions-response"

  functions-response:
    action: send
    channel:
      $ref: "#/channels/functions-response"

  location-request:
    action: receive
    channel:
      $ref: "#/channels/location-request"
    reply:
      channel:
        $ref: "#/channels/location-response"

  location-response:
    action: send
    channel:
      $ref: "#/channels/location-response"

  locations-request:
    action: receive
    channel:
      $ref: "#/channels/locations-request"
    reply:
      channel:
        $ref: "#/channels/locations-response"

  locations-response:
    action: send
    channel:
      $ref: "#/channels/locations-response"

  datapoint-write-indication:
    action: send
    channel:
      $ref: "#/channels/datapoint-write-indication"

  datapoint-write-request:
    action: receive
    channel:
      $ref: "#/channels/datapoint-write-request"
